name: main

on:
  push: 
    branches: [ main ] 
   
env:
  DOTNET_VERSION: 5.0.x
  
jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      dot-version: ${{ steps.store.outputs.dot-version }}
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: print
      run: |
        echo DOTNET_VERSION=${{env.DOTNET_VERSION}}
        echo version=${DOTNET_VERSION}
        echo version=$DOTNET_VERSION
      
    - name: store
      id: store
      run: echo "::set-output name=dot-version::${{env.DOTNET_VERSION}}"
      
  test:
    needs: [ main ]
    runs-on: ubuntu-latest
    steps:
    - name: print
      run: echo from last step ${{needs.main.outputs.dot-version}}

  cd:
    needs: []
    runs-on: ubuntu
    steps:
    - name: mkdir
      run: mkdir 5.0.x
    - name: pwd
      working-directory: 5.0.x
      run: pwd
    
  reuse:  
    needs: [ main ]
    uses: tjcorr/variable-to-reusable-workflow/.github/workflows/reusable.yml@main
    with:
      param: ${{needs.main.outputs.dot-version}}
      #param: ${{env.DOTNET_VERSION}}
