name: Reusable

on:
  workflow_call:
    inputs:
      param:
        required: true
        type: string
 
jobs:
  test:
     runs-on: ubuntu-latest
     
     steps:
     - name: output
       run: echo Resuable workflow was passed in ${{ inputs.param }}
